# Generated by Django 5.0.1 on 2024-04-03 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tematica',
            options={},
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nacionality',
        ),
        migrations.AddField(
            model_name='autor',
            name='nationality',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='libro',
            name='year_editorial',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='autor',
            name='surname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='tematica',
        ),
        migrations.AlterField(
            model_name='libro',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='year_of_edition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tematica',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.editorial'),
        ),
        migrations.AddField(
            model_name='libro',
            name='tematica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tematica'),
        ),
    ]
